sudo: required
services:
  - docker

before_install:
  - docker build -t zoominggg/react-test -f ./client/Dockerfile.test ./client

script:
  - docker run -e CI=true zoominggg/react-test npm test

after_success:
  - docker build -t zoominggg/multi-client ./client
  - docker build -t zoominggg/multi-nginx ./nginx
  - docker build -t zoominggg/multi-server ./server
  - docker build -t zoominggg/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push zoominggg/multi-client
  - docker push zoominggg/multi-nginx
  - docker push zoominggg/multi-server
  - docker push zoominggg/multi-worker
